spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: serviceAdmin
        uri: lb://service-admin
        predicates:
        - Path=/srvadmin/**
        filters:
        - RewritePath=/srvadmin/(?<segment>.*), /$\{segment}
        - name: Hystrix
          args:
            name: monitor-srvAdmin
            fallbackUri: forward:/fallback/serviceAdmin
      - id: ServiceCompany
        uri: lb://service-Company
        predicates:
        - Path=/srvcompany/**
        filters:
        - RewritePath=/srvcompany/(?<segment>.*), /$\{segment}
        - name: Hystrix
          args:
            name: monitor-srvCompany
            fallbackUri: forward:/fallback/serviceCompany
        - id: ServiceCustomer
        uri: lb://service-Customer
        predicates:
        - Path=/srvcustomer/**
        filters:
        - RewritePath=/srvcustomer/(?<segment>.*), /$\{segment}
        - name: Hystrix
          args:
            name: monitor-srvCustomer
            fallbackUri: forward:/fallback/serviceCustomer
      - id: MQActivityService
        uri: lb://activity
        predicates:
        - Path=/act/**
        filters:
        - RewritePath=/act/(?<segment>.*), /$\{segment} 
    consul:
      discovery:
        instanceId: Gateway
        health-check-interval: 5s
      config:
        management: 
          enabled: true
management:
  security: 
    enabled: false
  endpoints:
    web:
      exposure:
        include: hystrix.stream, info, health
     
